// main language
export const EMAIL_TEXT = 'Email';
export const PASSWORD_TEXT = 'Contraseña';
export const LOGIN_TEXT = 'Iniciar';
export const FORGOT_PASSWORD_TEXT = 'Se te olvidó tu contraseña';
export const SIGN_UP_TEXT = 'Regístrate';
export const VIN_NUM = 'VIN Numero';
export const PLATE_NUM = 'License Plate';
export const VEHICLE_TYPE = 'Bike Type';
export const NAME_TEXT = 'Name';
export const GPS_WARNING_CLIENT = 'Debe tener GPS habilitado para usar esta función. Recuerde que los usuarios cercanos a usted pueden ver su ubicación en un mapa.';
export const CLIENT_READY = '¿Estás listo para solicitar un viaje?';
export const RIDE_INSTRUCTIONS = 'Introduzca cualquier instrucción especial o instrucciones.'
export const READY = 'Listo';
export const CANCEL = 'Cancelar';
export const IS_ON_THE_WAY = ' está en el camino';
export const MARK_JOB_COMPLETE = 'Trabajo Completo';
export const JOB_PAGE_INSTRUCTIONS = 'Instrucciones:';
export const CLIENT_NAME = 'Nombre del cliente:';
export const RIDER_OLD_JOB_WARNING = 'Este es un viejo trabajo. Recuerde que debe completar los trabajos anteriores antes de tomar uno nuevo.';
export const MAIN_TITLE = 'MiMotor';
export const REGISTER = 'Registro';
export const WORKING = 'Trabajando';
export const JOB_LIST = 'Lista de trabajos';
export const TAKE_JOB = 'Tómalo';

// english
export const E_EMAIL_TEXT = 'Email';
export const E_PASSWORD_TEXT = 'Password';
export const E_LOGIN_TEXT = 'Login';
export const E_FORGOT_PASSWORD_TEXT = 'Forgot your password?';
export const E_SIGN_UP_TEXT = 'Register';
export const E_NAME_TEXT = 'Name';
export const E_GPS_WARNING_CLIENT = 'You must have GPS enabled to use this feature. Remember riders close to you can see your location on a map.';
export const E_CLIENT_READY = 'Are you ready to request a ride?';
export const E_RIDE_INSTRUCTIONS = 'Enter any special instructions or directions.'
export const E_READY = 'Ready';
export const E_CANCEL = 'Cancel';
export const E_IS_ON_THE_WAY = ' is on the way';
export const E_MAIN_TITLE = 'MiMotor';
export const E_REGISTER = 'Register';
export const E_JOB_LIST = 'Job List';
